### ISSUE TITLE
Discord api error

### ISSUE THREAD

**Issue by RYHTN** [y21/serverbuild#3]
=== An error occurred ===
DiscordAPIError: Invalid Form Body
bitrate: int değeri en az 8000 olmalıdır.
    at item.request.gen.end (C:\Users\askse\Desktop\serverbuild-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15)
    at then (C:\Users\askse\Desktop\serverbuild-master\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by RYHTN** [comment]
=== An error occurred ===
TypeError: Cannot read property 'name' of null
    at targetChannel.setParent.guild.channels.find.channel (C:\Users\askse\Desktop\serverbuild-master\index.js:133:114)
    at Map.find (C:\Users\askse\Desktop\serverbuild-master\node_modules\discord.js\src\util\Collection.js:506:11)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\askse\Desktop\serverbuild-master\index.js:133:66)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Red09discord** [comment]
Yeah it's a bitrate error I've had it too I'm waiting for y21 to fix it xD

**Comment by y21** [comment]
Sorry, I only saw this issue now. I will work on this ASAP.

**Comment by y21** [comment]
Fixed.
