### ISSUE TITLE
err

### ISSUE THREAD

**Issue by SSTheLegend** [y21/serverbuild#4]
Received code. Getting information...
Server will be created in 10 seconds. To cancel, press CTRL + C.
Created roles!
=== An error occurred ===
DiscordAPIError: Invalid Form Body
bitrate: int value should be greater than or equal to 8000.
    at item.request.gen.end (/rbd/pnpm-volume/a1d3b4bd-6662-4dd2-bd01-ad9e040effbf/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/rbd/pnpm-volume/a1d3b4bd-6662-4dd2-bd01-ad9e040effbf/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by CristiPet** [comment]
That means that the server you wanna backup have nitro boosting and the channels have a bitrate over 96kbps. You should set manually in the code the bitrate to 64 or 96 (Your choice) to make it work properly

**Comment by FrancisB1000** [comment]
How do you manually set it?

**Comment by lulu2411** [comment]
I have the same issue.
